site_name: Key Mapper Documentation
site_author: sds100
repo_url: https://github.com/sds100/KeyMapper
site_description: Documentation website for the Key Mapper Android app.
nav:
    - Home: index.md
    - Contributing: contributing.md
    - User Guide:
        - Triggers: user-guide/triggers.md
        - Actions: user-guide/actions.md

theme:
  name: material
  palette:
    accent: red
  favicon: images/favicon.ico
  logo: images/logo.png

extra_css:
- stylesheets/extra.css